export const signUp = async( req,res,next )=>{
  try{

  }
  catch(err){
    next(err)
  }
}

export const logIn = async( req,res,next )=>{
    try{
  
    }
    catch(err){
      next(err)
    }
  }